name = "art-playground"
main = "./worker.js"
compatibility_date = "2026-09-03"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*", "/", "/index.html"]

[[d1_databases]]
binding = "DB"
database_name = "art-playground-votes"
database_id = "b9edec56-cba5-40f5-a86f-cc0cdea7da90"
