/* LIVING20 — ChatGPT作。v30 + Ambients inspired living fractal engine. */
(function(){'use strict';
const TAU=Math.PI*2;
const titles=['MEMORY','PRESSURE','GRAVITY','ECHO','CURRENT','SCAR','TIDE','MIRROR','SPLIT','WORMHOLE','VEIL','FOLD','ORBIT','RESONANCE','CRYSTAL','DRIFT','VORTEX','FRACTURE','NEST','VOID'];
const desc=['memory topology','recursive pressure','persistent attractors','multi-scale echoes','living currents','long scars','breathing tide','local symmetry','branching split','depth warp','phase veil','deep folds','orbit law','resonant bands','organic lattice','slow drift','nested vortices','broken topology','self-similar nesting','living void'];
const canvas=document.querySelector('canvas'); const gl=canvas.getContext('webgl2',{antialias:false,alpha:false});
if(!gl){document.body.innerHTML='<pre>WebGL2 required</pre>';return;}
const V=`#version 300 es\nprecision highp float;\nin vec2 p; void main(){gl_Position=vec4(p,0.,1.);}`;
const FS=`#version 300 es\nprecision highp float;\nout vec4 o; uniform vec2 r; uniform float t,mode,seed; uniform sampler2D law;\n#define PI 3.14159265359\nfloat h21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}\nvec2 rot(vec2 p,float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c)*p;}\nfloat fold(vec2 p){for(int i=0;i<7;i++){p=abs(p);p-=.52;p=rot(p,.42+sin(seed+float(i))*0.28);p*=1.43;}return length(p);}\nfloat field(vec2 p){float v=0.;float sc=1.;for(int i=0;i<5;i++){v+=sin(p.x*sc+sin(p.y*sc+t*.35))*cos(p.y*sc-p.x*sc*.37+t*.21)/sc;p=rot(p,.61)+vec2(.13,-.07);sc*=1.83;}return v;}\nvec3 pal(float x){vec3 a=vec3(.5),b=vec3(.5),c=vec3(1.),d=vec3(.00,.18,.37);return a+b*cos(6.28318*(c*x+d+vec3(seed*.07,seed*.11,seed*.17)));}\nvoid main(){vec2 uv=(gl_FragCoord.xy-.5*r)/min(r.x,r.y); float R=length(uv);\nvec4 L=texture(law,fract(gl_FragCoord.xy/r)); float m=L.r,g=L.g,b=L.b;\nvec2 q=uv; float ang=atan(q.y,q.x);\nif(mode<.5){q=rot(q,m*1.8); q*=1.+m*.75*sin(ang*8.+t);}\nelse if(mode<1.5){q=rot(q,g*2.5); q*=1.-g*.5*cos(ang*12.);}\nelse if(mode<2.5){q-=.18*vec2(cos(ang*3.+m*5.),sin(ang*3.+m*5.))*m; q=rot(q,b*3.);}\nelse if(mode<3.5){q+=.08*sin(q.yx*18.+m*8.+t); q=rot(q,sin(ang*5.)*m);}\nelse if(mode<4.5){q+=.12*vec2(sin(q.y*9.+t),cos(q.x*9.-t))*g; q=rot(q,m*2.);}\nelse if(mode<5.5){q+=normalize(q+.0001)*m*.22; q=rot(q,-m*2.);}\nelse if(mode<6.5){q*=1.+sin(t+R*9.)*.055; q+=vec2(cos(t*.5),sin(t*.5))*.025*m;}\nelse if(mode<7.5){q=abs(q); if(q.x<q.y)q=q.yx; q=rot(q,m*PI/3.);}\nelse if(mode<8.5){float a=atan(q.y,q.x);a+=m*sin(a*3.)*.8;q=vec2(cos(a),sin(a))*R;}\nelse if(mode<9.5){q*=1.+m*.9/(.15+R);q=rot(q,6.*m/(.2+R));}\nelse if(mode<10.5){q=rot(q,b*3.); q*=1.+.18*sin(q.x*14.+q.y*11.+t)*m;}\nelse if(mode<11.5){q=abs(q);q=rot(q,.7);for(int i=0;i<5;i++){q=abs(q)-.31;q=rot(q,.35+m*.8);q*=1.55;}}\nelse if(mode<12.5){float a=ang+g*5.;q=vec2(cos(a),sin(a))*R; q+=.08*vec2(cos(a*7.+t),sin(a*7.+t))*m;}\nelse if(mode<13.5){q.x+=.12*sin(q.y*22.+t*2.)*m;q.y+=.12*sin(q.x*17.-t*1.7)*g;}\nelse if(mode<14.5){q=rot(q,m*.9);q=abs(q)-.18; q*=2.25; q=rot(q,g*1.7);}\nelse if(mode<15.5){q+=.035*vec2(sin(q.y*13.+t),cos(q.x*11.-t))*m; q=rot(q,t*.04+g);}\nelse if(mode<16.5){for(int i=0;i<4;i++){q=rot(q,.9);q+=vec2(.23,-.08)*sin(float(i)+t*.4)*m;q=abs(q)-.22;q*=1.55;}}\nelse if(mode<17.5){float a=atan(q.y,q.x);float k=floor(a/(PI/3.));a-=k*PI/3.;q=vec2(cos(a),sin(a))*R;q+=normalize(q+.001)*m*.12*sin(k+g*5.);}\nelse if(mode<18.5){q=abs(q);q-=.36; q=rot(q,m*2.);q*=1.35+g*.4;}\nelse {q=rot(q,m*2.);q*=1.+.25*sin(R*12.-t*.5)*g;q+=normalize(q+.001)*b*.12;}\nfloat f=field(q*2.0); float fr=fold(q*1.45+f*.12); float bands=sin(fr*15.-t*.8+f*2.4); float glow=smoothstep(1.25,.05,fr);\nfloat v=.5+.5*(.55*f+.65*bands); v+=m*.22+g*.12; vec3 col=pal(v+fr*.12); col*=.45+1.15*glow; col+=pal(v+.33)*.22*pow(max(0.,bands),4.);\nfloat vign=smoothstep(1.5,.12,R); col*=vign; o=vec4(col,1.);}`;
function sh(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s} let pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,V));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,FS));gl.linkProgram(pr);gl.useProgram(pr);
let buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);let loc=gl.getAttribLocation(pr,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);
let law=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,law);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);let N=192;let data=new Uint8Array(N*N*4);for(let i=0;i<N*N;i++){data[i*4]=128;data[i*4+1]=128;data[i*4+2]=128;data[i*4+3]=255;}gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,N,N,0,gl.RGBA,gl.UNSIGNED_BYTE,data);
const uR=gl.getUniformLocation(pr,'r'),uT=gl.getUniformLocation(pr,'t'),uM=gl.getUniformLocation(pr,'mode'),uS=gl.getUniformLocation(pr,'seed');let mode=+canvas.dataset.mode||0,seed=Math.random()*100,marks=[];let phase=0;
function resize(){let d=Math.min(devicePixelRatio||1,1.5),w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}addEventListener('resize',resize);resize();
function paint(x,y,rad=30){let cx=Math.floor(x/innerWidth*N),cy=Math.floor((1-y/innerHeight)*N),rr=Math.max(3,Math.floor(rad/innerWidth*N));for(let yy=-rr;yy<=rr;yy++)for(let xx=-rr;xx<=rr;xx++){let X=cx+xx,Y=cy+yy;if(X<0||X>=N||Y<0||Y>=N)continue;let d=Math.hypot(xx,yy)/rr;if(d>1)continue;let k=(Y*N+X)*4, q=1-d;data[k]=Math.min(255,data[k]+70*q);data[k+1]=Math.min(255,data[k+1]+(mode%3===0?55:25)*q);data[k+2]=Math.min(255,data[k+2]+(mode%3===2?65:30)*q);}gl.bindTexture(gl.TEXTURE_2D,law);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,N,N,gl.RGBA,gl.UNSIGNED_BYTE,data)}
function reset(){data.fill(128);for(let i=3;i<data.length;i+=4)data[i]=255;marks=[];seed=Math.random()*100;}
function mutate(){seed=Math.random()*100;mode=(mode+Math.floor(Math.random()*19)+1)%20;canvas.dataset.mode=mode;}
function render(ti=performance.now()/1000){gl.useProgram(pr);gl.uniform2f(uR,canvas.width,canvas.height);gl.uniform1f(uT,ti);gl.uniform1f(uM,mode);gl.uniform1f(uS,seed);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,law);gl.uniform1i(gl.getUniformLocation(pr,'law'),0);gl.drawArrays(gl.TRIANGLES,0,6);requestAnimationFrame(render)}
canvas.addEventListener('pointerdown',e=>{let x=e.clientX,y=e.clientY;if(window.APKit&&APKit.isUI(x,y))return true;paint(x,y,45);return false});canvas.addEventListener('pointermove',e=>{if(e.buttons){let x=e.clientX,y=e.clientY;if(window.APKit&&APKit.isUI(x,y))return true;paint(x,y,22);return false}});
render();
APKit.init({canvas,gifName:'living20-'+String(mode+1).padStart(2,'0')+'-'+titles[mode].toLowerCase()+'-loop',clockFormat:'spec',loopFrame:function(p){phase=p;gl.uniform1f(uT,phase);gl.uniform1f(uM,mode);gl.uniform1f(uS,seed);gl.drawArrays(gl.TRIANGLES,0,6)},buttons:[{label:'✦',name:'mutate',onClick:mutate},{label:'↻',name:'reset',onClick:reset}]});
window.LIVING20={titles,desc,get mode(){return mode},setMode:n=>{mode=(n+20)%20;canvas.dataset.mode=mode;}};
})();